packages:
  - "core"
  - "ui"
  - "gui"
  - "evals"
  - "server"
  - "mcp-servers/novel-fetch"

allowBuilds:
  better-sqlite3: true
  esbuild: true
  zeromq: true

onlyBuiltDependencies:
  - zeromq
  - esbuild
  - better-sqlite3
